### PR TITLE
Don't use _Py_IDENTIFIER() APIs

### LINKED ISSUE #31: Drop _Py_IDENTIFIER API usage
See https://bugs.python.org/issue46541 and 

The _Py_IDENTIFIER APIs will probably not be dropped from the CPython (internal) C API (yet), but removing usage from 3rd party projects will definitely help :)

The `self.cursor()` calls in `connection.c` can easily be inlined, with a performance gain; call `pysqlite_connection_cursor()` directly from `pysqlite_connection_execute*()` instead of going through 6 or 7 (!) function calls.

Future optimisation:
- The `upper()` call in `pysqlite_connection_create_collation()` can be removed (take a look at python/cpython#27395)
- Consider using interned strings for the `value` and `finalize` calls

### PR DESCRIPTION
**Pull request by erlend-aasland**
Resolves #31

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Disclaimer: I haven't had the time to test (or even compile) these changes yet. I'll get around to doing that later today, but the changes are pretty straight-forward; it should work straight out of the box.

**Comment by coleifer** [comment]
I'm going to pass for now, but will reconsider it should the upstream APIs also change.

**Comment by coleifer** [comment]
Aaaactually, hmm... Let me reconsider.

**Comment by coleifer** [comment]
FYI these are *not* merged, accidentally hit the merge button and force-pushed to restore the original head.

**Comment by coleifer** [comment]
There seems to be a few issues with these changes, even after I've got them compiling, so I'm going to return to my earlier stance:

I'm going to pass for now, but will reconsider it should the upstream APIs also change.

**Pull request merged**
